name: smart_truck_app
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  introduction_screen: ^4.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4
  equatable: ^2.0.7
  dartz: ^0.10.1
  http: ^1.2.2
  internet_connection_checker: ^3.0.1
  # flutter_local_notifications: ^18.0.1
  get_it: ^9.2.0
  easy_localization: ^3.0.7
  retrofit: ^4.2.0
  pretty_dio_logger: ^1.4.0
  data_connection_checker_nulls: ^0.0.2
  logger: ^2.6.2
  json_annotation: ^4.9.0
  dio: ^5.6.0
  # equatable: ^2.0.5
  # flutter_bloc: ^8.1.6
  json_serializable: ^6.8.0
  animated_icon: ^0.0.9
  carousel_slider: ^5.0.0
  retrofit_generator: ^8.2.0
  analyzer: ^6.4.1
  shimmer: ^3.0.0
  webview_flutter: ^4.6.0
  lottie: ^3.1.3
  # image_picker: ^1.0.8
  path: ^1.9.0
  sqflite: ^2.3.3+1
  flutter_cached_pdfview: ^0.4.3
  animated_theme_switcher: ^2.0.10
  intl: ^0.20.2
  # shared_preferences: ^2.5.3
  flutter_form_builder: ^10.1.0
  form_builder_validators: ^11.2.0
  pin_code_fields: ^8.0.1
  fluttertoast: ^8.2.12
  modal_bottom_sheet: ^3.0.0
  flutter_spinkit: ^5.2.2
  animate_do: ^4.2.0
  visibility_detector: ^0.4.0+2
  connectivity_plus: ^6.1.5
  build_runner: ^2.4.13
  image_picker: ^1.2.1
  dotted_line: ^3.2.3
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7


# ========================
# SPLASH SCREEN CONFIGURATION
# ========================
flutter_native_splash:
  android: true
  ios: true
  # image: assets/images/default.png
  color: "#000000"

  android_12:
    color: "#E8F5E9 "
    image: assets/images/default.png

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
